name: Building Twrp

on:
  workflow_dispatch:

env:
  # (required) twrp manifest 
  MANIFEST: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git
  # (required) manifest branch 
  BRANCH: twrp-10.0-deprecated
  # (required) device codename i.e: sweet mojito.. 
  DEVICE: f12
  # (required) device tree link with branch if exists
  DT_LINK: https://github.com/boudamoney/test.git
  # (required) who made your phone ? 
  MANUFACTURER: samsung
  # (required) recovery partiton = recovery, else (no recovery partition): boot 
  TARGET: recovery
  # dont change that
  IMAGE: image
  # (required) depend of device tree if you see twrp_"codename".mk use twrp
  # else (omni_"codename".mk): omni
  OT: omni
  # dont change that
  SYM: _

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
                               
       - name: Setting repo binary
         run: |
            sudo apt update && sudo apt install git
            git clone https://github.com/boudamoney/rm_pkg pkg && cd pkg && bash setup.sh
            cd .. && sudo -E apt-get -qq update
            sudo -E apt-get -qq install bc build-essential tar zip curl libstdc++6 git wget python gcc clang libssl-dev rsync flex curl ccache bison aria2
            sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
            sudo chmod a+rx /usr/local/bin/repo
            
       - name: Adding and Sync source
         run: |   
             mkdir work
             cd work
             echo -ne '\n' | repo init -m $MANIFEST -b $BRANCH --depth=1      
             repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
             git clone https://github.com/boudamoney/android_device_samsung_f12-TWRP.git -b master device/samsung/f12/
             
       - name: Build twrp
         run: |
              cd work
              tar_path=$(pwd)
              . build/envsetup.sh && lunch omni_f12-eng && make -j$(nproc --all) recoveryimage
              sudo tar -zcvf /home/runner/twrp.tar.gz $tar_path/out/target/product/f12/recovery.img

       - name: Save in artifact
         uses: actions/upload-artifact@v3
         with:
            name: recovery.tar.gz
            path: /home/runner/twrp.tar.gz
            retention-days: 5
