name: Building Twrp

on:
  workflow_dispatch:

env:
  # (required) twrp manifest 
  MANIFEST: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git
  # (required) manifest branch 
  BRANCH: twrp-11
  # (required) device codename i.e: sweet mojito.. 
  DEVICE: f12
  # (required) device tree link with branch if exists
  DT_LINK: https://github.com/boudamoney/test.git
  # (required) who made your phone ? 
  MANUFACTURER: samsung
  # (required) recovery partiton = recovery, else (no recovery partition): boot 
  TARGET: recovery
  # dont change that
  IMAGE: image
  # (required) depend of device tree if you see twrp_"codename".mk use twrp
  # else (omni_"codename".mk): omni
  OT: twrp
  # dont change that
  SYM: _

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
                               
       - name: setting repo
         run: |
            sudo apt update && sudo apt install git
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install bc build-essential tar zip curl libstdc++6 git wget python gcc clang libssl-dev repo rsync flex curl  bison aria2
            sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
            sudo chmod a+rx /usr/local/bin/repo
            
       - name: Adding and Sync source
         run: |   
             mkdir work
             cd work
             repo init -u $MANIFEST -b $BRANCH          
             repo sync -v -c -j700 --force-sync --no-clone-bundle --no-tags
             git clone $DT_LINK device/$MANUFACTURER/$DEVICE
             
       - name: Build twrp
         run: |
              cd work
              tar_path=$(pwd)
              export ALLOW_MISSING_DEPENDENCIES=true && . build/envsetup.sh && lunch $OT$SYM$DEVICE-user && mka recoveryimage
              sudo tar -zcvf /home/runner/twrp.tar.gz $tar_path/out/target/product/$DEVICE

       - name: Save in artifact
         uses: actions/upload-artifact@v3
         with:
            name: recovery.tar.gz
            path: /home/runner/twrp.tar.gz
            retention-days: 5
